name: Release
on:
  create:
    tages:
    - v*

jobs:
  release:
    name: Release on github
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./module_03/homework03_1/
          file: ./module_03/homework03_1/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/httpserver:${{steps.get_version.outputs.VERSION}}