apiVersion: v1
kind: ConfigMap
metadata:
  name: httpserver-version
data:
  version: "v0.5.0"
---
apiVersion: v1
kind: Service
metadata:
  name: httpserver
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpserver
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: httpserver
        image: summingyu/httpserver:v0.3.0
        ports:
        - containerPort: 80
        env:
          - name: VERSION
            valueFrom:
              configMapKeyRef:
                key: version
                name: httpserver-version
                optional: true
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - 5s